project:
  type: website
  output-dir: docs

website:
  title: "Levi Denissen"
  page-footer: 
    background: 'dark'
    left: Copyright 2025, Levi Denissen
    right: This website was built with Github, Rstudio, and Quarto
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.pdf
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full

editor: visual

